from enum import Enum

class Tag(Enum):
    AIML        = "aiml"
    CATEGORY    = "category"
    PATTERN     = "pattern"
    TEMPLATE    = "template"
    THAT        = "that"
    THINK       = "think"
    SET         = "set"
    GET         = "get"
    STAR        = "star"
    SRAI        = "srai"

ENTITY_MAP = {
    # ORG (Organizations / Roles)
    "công ty": "ORG",
    "đơn vị": "ORG",
    "đơn vị bạn": "ORG",
    "khách hàng": "ORG",
    "đối tác": "ORG",
    "doanh nghiệp": "ORG",
    "tổ chức": "ORG",
    "phòng ban": "ORG",
    "bộ phận": "ORG",
    "chi nhánh": "ORG",
    "cơ quan": "ORG",
    "cơ quan nhà nước": "ORG",
    "cơ quan quản lý": "ORG",
    "ban lãnh đạo": "ORG",
    "hội đồng quản trị": "ORG",
    "nhà cung cấp": "ORG",
    "đối thủ cạnh tranh": "ORG",
    "nhà đầu tư": "ORG",
    "cổ đông": "ORG",
    "nhân viên": "ORG",
    "cán bộ": "ORG",
    "lãnh đạo": "ORG",
    "quản lý cấp cao": "ORG",
    "trưởng phòng": "ORG",
    "giám đốc": "ORG",
    "ceo": "ORG",
    "cto": "ORG",
    "cfo": "ORG",
    "team": "ORG",
    "nhóm": "ORG",
    "đội ngũ": "ORG",
    "user": "ORG",
    "người dùng": "ORG",
    "end user": "ORG",
    "admin": "ORG",
    "quản trị viên": "ORG",
    "khách hàng nội bộ": "ORG",
    "khách hàng bên ngoài": "ORG",
    "sinh viên": "ORG",
    "học viên": "ORG",
    "giảng viên": "ORG",
    "giáo viên": "ORG",
    "bệnh nhân": "ORG",
    "bác sĩ": "ORG",
    "y tá": "ORG",
    "dược sĩ": "ORG",
    "tài xế": "ORG",
    "nhân viên giao hàng": "ORG",
    "shipper": "ORG",
    "cư dân": "ORG",
    "chủ hộ": "ORG",
    "ban quản lý": "ORG",
    "ban quản trị": "ORG",
    "kỹ thuật viên": "ORG",
    "nhân viên hỗ trợ": "ORG",
    "tư vấn viên": "ORG",
    "sale": "ORG",
    "nhân viên kinh doanh": "ORG",
    "nhân viên chăm sóc khách hàng": "ORG",
    "cs": "ORG",
    "cskh": "ORG",
    "operator": "ORG",
    "moderator": "ORG",
    "biên tập viên": "ORG",
    "content creator": "ORG",
    "đối tác vận chuyển": "ORG",
    "đơn vị vận chuyển": "ORG",
    "nhà phát triển": "ORG",
    "developer": "ORG",
    "lập trình viên": "ORG",
    "qa": "ORG",
    "tester": "ORG",
    "devops engineer": "ORG",
    "data analyst": "ORG",
    "data engineer": "ORG",
    "product owner": "ORG",
    "product manager": "ORG",
    "ba": "ORG",
    "business analyst": "ORG",

    # SYS (Systems / Software / Infrastructure)
    "ứng dụng": "SYS",
    "hệ thống": "SYS",
    "nền tảng": "SYS",
    "hạ tầng mạng": "SYS",
    "phần mềm": "SYS",
    "software": "SYS",
    "hệ thống thông tin": "SYS",
    "hệ thống quản lý": "SYS",
    "erp": "SYS",
    "crm": "SYS",
    "hrm": "SYS",
    "hrms": "SYS",
    "lms": "SYS",
    "cms": "SYS",
    "dms": "SYS",
    "bpm": "SYS",
    "workflow": "SYS",
    "portal": "SYS",
    "cổng thông tin": "SYS",
    "website": "SYS",
    "web app": "SYS",
    "mobile app": "SYS",
    "ứng dụng di động": "SYS",
    "app": "SYS",
    "api": "SYS",
    "microservices": "SYS",
    "dịch vụ": "SYS",
    "service": "SYS",
    "server": "SYS",
    "máy chủ": "SYS",
    "cloud": "SYS",
    "điện toán đám mây": "SYS",
    "aws": "SYS",
    "azure": "SYS",
    "google cloud": "SYS",
    "database": "SYS",
    "cơ sở dữ liệu": "SYS",
    "db": "SYS",
    "sql": "SYS",
    "nosql": "SYS",
    "data warehouse": "SYS",
    "kho dữ liệu": "SYS",
    "data lake": "SYS",
    "hạ tầng": "SYS",
    "infrastructure": "SYS",
    "mạng": "SYS",
    "network": "SYS",
    "firewall": "SYS",
    "bảo mật": "SYS",
    "security": "SYS",
    "authentication": "SYS",
    "authorization": "SYS",
    "đăng nhập": "SYS",
    "sso": "SYS",
    "ldap": "SYS",
    "active directory": "SYS",
    "ci/cd": "SYS",
    "devops": "SYS",
    "container": "SYS",
    "docker": "SYS",
    "kubernetes": "SYS",
    "k8s": "SYS",
    "message queue": "SYS",
    "kafka": "SYS",
    "rabbitmq": "SYS",
    "cache": "SYS",
    "redis": "SYS",
    "load balancer": "SYS",
    "cdn": "SYS",
    "monitoring": "SYS",
    "logging": "SYS",
    "backup": "SYS",
    "sao lưu": "SYS",
    "recovery": "SYS",
    "khôi phục": "SYS",
    "oauth": "SYS",
    "oauth 2.0": "SYS",
    "oauth2": "SYS",
    "jwt": "SYS",
    "json web token": "SYS",
    "openid connect": "SYS",
    "saml": "SYS",
    "sso": "SYS",
    "mfa": "SYS",
    "2fa": "SYS",
    "otp": "SYS",
    "biometric": "SYS",
    "faceid": "SYS",
    "touchid": "SYS",
    "face recognition": "SYS",
    "nhận diện khuôn mặt": "SYS",
    "liveness detection": "SYS",
    "geofencing": "SYS",
    "device binding": "SYS",
    "postgresql": "SYS",
    "postgres": "SYS",
    "mysql": "SYS",
    "mongodb": "SYS",
    "redis": "SYS",
    "elasticsearch": "SYS",
    "opensearch": "SYS",
    "qdrant": "SYS",
    "vector database": "SYS",
    "vector db": "SYS",
    "kafka": "SYS",
    "rabbitmq": "SYS",
    "bullmq": "SYS",
    "websocket": "SYS",
    "socket.io": "SYS",
    "grpc": "SYS",
    "graphql": "SYS",
    "rest api": "SYS",
    "fcm": "SYS",
    "firebase": "SYS",
    "firebase cloud messaging": "SYS",
    "apns": "SYS",
    "s3": "SYS",
    "amazon s3": "SYS",
    "minio": "SYS",
    "cdn": "SYS",
    "cloudflare": "SYS",
    "cloudfront": "SYS",
    "vnpay": "SYS",
    "momo": "SYS",
    "payment gateway": "SYS",
    "cổng thanh toán": "SYS",
    "hls": "SYS",
    "webrtc": "SYS",
    "rtmp": "SYS",
    "ffmpeg": "SYS",
    "docker": "SYS",
    "kubernetes": "SYS",
    "k8s": "SYS",
    "github actions": "SYS",
    "gitlab ci": "SYS",
    "jenkins": "SYS",
    "prometheus": "SYS",
    "grafana": "SYS",
    "elk": "SYS",
    "elasticsearch logstash kibana": "SYS",
    "serilog": "SYS",
    "opentelemetry": "SYS",
    "jaeger": "SYS",
    "zipkin": "SYS",
    "vault": "SYS",
    "hashicorp vault": "SYS",
    "kms": "SYS",
    "aes-256": "SYS",
    "tls": "SYS",
    "ssl": "SYS",
    "waf": "SYS",
    "web application firewall": "SYS",
    "rate limiting": "SYS",
    "api gateway": "SYS",
    "service mesh": "SYS",
    "consul": "SYS",
    "istio": "SYS",
    "nginx": "SYS",
    "traefik": "SYS",
    "pgbouncer": "SYS",
    "proxysql": "SYS",
    "thiết bị di động": "SYS",
    "hệ thống thông báo": "SYS",

    # FEATURE (Business features / Outputs)
    "nhân sự": "FEATURE",
    "quản lý": "FEATURE",
    "quy trình": "FEATURE",
    "tự động hóa": "FEATURE",
    "báo cáo": "FEATURE",
    "tài liệu": "FEATURE",
    "thông tin": "FEATURE",
    "dữ liệu": "FEATURE",
    "thời gian thực": "FEATURE",
    "chi phí": "FEATURE",
    "lương": "FEATURE",
    "chấm công": "FEATURE",
    "tuyển dụng": "FEATURE",
    "đào tạo": "FEATURE",
    "đánh giá": "FEATURE",
    "kpi": "FEATURE",
    "hiệu suất": "FEATURE",
    "năng suất": "FEATURE",
    "doanh thu": "FEATURE",
    "lợi nhuận": "FEATURE",
    "doanh số": "FEATURE",
    "bán hàng": "FEATURE",
    "marketing": "FEATURE",
    "quảng cáo": "FEATURE",
    "khuyến mãi": "FEATURE",
    "sản phẩm": "FEATURE",
    "dịch vụ": "FEATURE",
    "đơn hàng": "FEATURE",
    "hóa đơn": "FEATURE",
    "thanh toán": "FEATURE",
    "giao hàng": "FEATURE",
    "kho": "FEATURE",
    "tồn kho": "FEATURE",
    "nhập kho": "FEATURE",
    "xuất kho": "FEATURE",
    "mua hàng": "FEATURE",
    "cung ứng": "FEATURE",
    "chuỗi cung ứng": "FEATURE",
    "sản xuất": "FEATURE",
    "vận hành": "FEATURE",
    "vận chuyển": "FEATURE",
    "logistics": "FEATURE",
    "khách hàng tiềm năng": "FEATURE",
    "lead": "FEATURE",
    "cơ hội bán hàng": "FEATURE",
    "opportunity": "FEATURE",
    "hợp đồng": "FEATURE",
    "thỏa thuận": "FEATURE",
    "dự án": "FEATURE",
    "task": "FEATURE",
    "công việc": "FEATURE",
    "ticket": "FEATURE",
    "yêu cầu": "FEATURE",
    "phản hồi": "FEATURE",
    "feedback": "FEATURE",
    "khiếu nại": "FEATURE",
    "hỗ trợ": "FEATURE",
    "support": "FEATURE",
    "dashboard": "FEATURE",
    "biểu đồ": "FEATURE",
    "thống kê": "FEATURE",
    "phân tích": "FEATURE",
    "analytics": "FEATURE",
    "báo cáo tài chính": "FEATURE",
    "báo cáo doanh thu": "FEATURE",
    "báo cáo nhân sự": "FEATURE",
    "export": "FEATURE",
    "xuất file": "FEATURE",
    "import": "FEATURE",
    "nhập dữ liệu": "FEATURE",
    "đồng bộ": "FEATURE",
    "sync": "FEATURE",
    "thông báo": "FEATURE",
    "notification": "FEATURE",
    "email": "FEATURE",
    "sms": "FEATURE",
    "push notification": "FEATURE",
    "phân quyền": "FEATURE",
    "role": "FEATURE",
    "permission": "FEATURE",
    "audit log": "FEATURE",
    "nhật ký": "FEATURE",
    "lịch sử": "FEATURE",
    "version": "FEATURE",
    "phiên bản": "FEATURE",
    "workflow approval": "FEATURE",
    "phê duyệt": "FEATURE",
    "duyệt": "FEATURE",
    "tự động": "FEATURE",
    "automation": "FEATURE",
    "rule": "FEATURE",
    "quy tắc": "FEATURE",
    "cấu hình": "FEATURE",
    "setting": "FEATURE",
    "tùy chỉnh": "FEATURE",
    "customization": "FEATURE",
    "template": "FEATURE",
    "mẫu": "FEATURE",
    "form": "FEATURE",
    "biểu mẫu": "FEATURE",
    "search": "FEATURE",
    "tìm kiếm": "FEATURE",
    "filter": "FEATURE",
    "lọc": "FEATURE",
    "sort": "FEATURE",
    "sắp xếp": "FEATURE",
    "pagination": "FEATURE",
    "phân trang": "FEATURE",
    "upload": "FEATURE",
    "tải lên": "FEATURE",
    "download": "FEATURE",
    "tải xuống": "FEATURE",
    "preview": "FEATURE",
    "xem trước": "FEATURE",
    "print": "FEATURE",
    "in ấn": "FEATURE",
    "chi phí vận hành": "FEATURE",
    "chi phí nhân sự": "FEATURE",
    "roi": "FEATURE",
    "hiệu quả": "FEATURE",
    "tối ưu": "FEATURE",
    "optimization": "FEATURE",
    "chấm công thông minh": "FEATURE",
    "chấm công khuôn mặt": "FEATURE",
    "tính lương": "FEATURE",
    "tính lương tự động": "FEATURE",
    "bảng lương": "FEATURE",
    "nghỉ phép": "FEATURE",
    "đơn nghỉ phép": "FEATURE",
    "onboarding": "FEATURE",
    "tuyển dụng": "FEATURE",
    "hồ sơ nhân sự": "FEATURE",
    "e-profile": "FEATURE",
    "kpi": "FEATURE",
    "okr": "FEATURE",
    "đánh giá hiệu suất": "FEATURE",
    "turnover": "FEATURE",
    "tỷ lệ nghỉ việc": "FEATURE",
    "giỏ hàng": "FEATURE",
    "cart": "FEATURE",
    "flash sale": "FEATURE",
    "mã giảm giá": "FEATURE",
    "voucher": "FEATURE",
    "coupon": "FEATURE",
    "loyalty": "FEATURE",
    "tích điểm": "FEATURE",
    "đổi quà": "FEATURE",
    "affiliate": "FEATURE",
    "referral": "FEATURE",
    "giới thiệu": "FEATURE",
    "tồn kho": "FEATURE",
    "kiểm kê": "FEATURE",
    "nhập kho": "FEATURE",
    "xuất kho": "FEATURE",
    "đặt hàng lại": "FEATURE",
    "reorder point": "FEATURE",
    "gợi ý sản phẩm": "FEATURE",
    "recommendation": "FEATURE",
    "cá nhân hóa": "FEATURE",
    "tìm kiếm thông minh": "FEATURE",
    "autocomplete": "FEATURE",
    "fuzzy search": "FEATURE",
    "đánh giá sản phẩm": "FEATURE",
    "review": "FEATURE",
    "rating": "FEATURE",
    "live streaming": "FEATURE",
    "phát trực tiếp": "FEATURE",
    "hóa đơn điện tử": "FEATURE",
    "e-invoice": "FEATURE",
    "chữ ký số": "FEATURE",
    "e-sign": "FEATURE",
    "hợp đồng điện tử": "FEATURE",
    "e-contract": "FEATURE",
    "phê duyệt": "FEATURE",
    "workflow": "FEATURE",
    "kanban": "FEATURE",
    "task management": "FEATURE",
    "quản lý công việc": "FEATURE",
    "dashboard": "FEATURE",
    "báo cáo tự động": "FEATURE",
    "thông báo realtime": "FEATURE",
    "push notification": "FEATURE",
    "chat": "FEATURE",
    "trò chuyện": "FEATURE",
    "omnichannel": "FEATURE",
    "đa kênh": "FEATURE",
    "cdp": "FEATURE",
    "customer data platform": "FEATURE",
    "ekyc": "FEATURE",
    "định danh điện tử": "FEATURE",
    "ocr": "FEATURE",
    "nhận dạng ký tự": "FEATURE",
    "rag": "FEATURE",
    "retrieval augmented generation": "FEATURE",
    "chatbot": "FEATURE",
    "trợ lý ảo": "FEATURE",
    "sentiment analysis": "FEATURE",
    "phân tích cảm xúc": "FEATURE",
    "fraud detection": "FEATURE",
    "phát hiện gian lận": "FEATURE",
    "geofencing": "FEATURE",
    "device binding": "FEATURE",
    "audit log": "FEATURE",
    "nhật ký hệ thống": "FEATURE",
    "session replay": "FEATURE",
    "heatmap": "FEATURE",
    "a/b testing": "FEATURE",
    "feature flag": "FEATURE",
    "feature toggle": "FEATURE",

    "oauth": "TECH",
    "oauth 2.0": "TECH",
    "oauth2": "TECH",
    "jwt": "TECH",
    "json web token": "TECH",
    "openid connect": "TECH",
    "oidc": "TECH",
    "saml": "TECH",
    "saml 2.0": "TECH",
    "mfa": "TECH",
    "2fa": "TECH",
    "otp": "TECH",
    "totp": "TECH",
    "biometric": "TECH",
    "face recognition": "TECH",
    "nhận diện khuôn mặt": "TECH",
    "liveness detection": "TECH",
    "geofencing": "TECH",
    "device binding": "TECH",
    "fingerprint": "TECH",
    "postgresql": "TECH",
    "postgres": "TECH",
    "mysql": "TECH",
    "mongodb": "TECH",
    "redis": "TECH",
    "elasticsearch": "TECH",
    "opensearch": "TECH",
    "qdrant": "TECH",
    "weaviate": "TECH",
    "pinecone": "TECH",
    "vector database": "TECH",
    "vector db": "TECH",
    "kafka": "TECH",
    "rabbitmq": "TECH",
    "bullmq": "TECH",
    "celery": "TECH",
    "websocket": "TECH",
    "socket.io": "TECH",
    "sse": "TECH",
    "server-sent events": "TECH",
    "grpc": "TECH",
    "graphql": "TECH",
    "rest": "TECH",
    "rest api": "TECH",
    "fcm": "TECH",
    "firebase cloud messaging": "TECH",
    "apns": "TECH",
    "s3": "TECH",
    "amazon s3": "TECH",
    "minio": "TECH",
    "cloudflare": "TECH",
    "cloudfront": "TECH",
    "cdn": "TECH",
    "vnpay": "TECH",
    "momo": "TECH",
    "stripe": "TECH",
    "paypal": "TECH",
    "hls": "TECH",
    "dash": "TECH",
    "webrtc": "TECH",
    "rtmp": "TECH",
    "ffmpeg": "TECH",
    "docker": "TECH",
    "kubernetes": "TECH",
    "k8s": "TECH",
    "helm": "TECH",
    "github actions": "TECH",
    "gitlab ci": "TECH",
    "jenkins": "TECH",
    "prometheus": "TECH",
    "grafana": "TECH",
    "elk stack": "TECH",
    "elasticsearch logstash kibana": "TECH",
    "serilog": "TECH",
    "opentelemetry": "TECH",
    "jaeger": "TECH",
    "zipkin": "TECH",
    "hashicorp vault": "TECH",
    "vault": "TECH",
    "kms": "TECH",
    "aes": "TECH",
    "aes-256": "TECH",
    "rsa": "TECH",
    "tls": "TECH",
    "ssl": "TECH",
    "mtls": "TECH",
    "waf": "TECH",
    "rate limiting": "TECH",
    "token bucket": "TECH",
    "leaky bucket": "TECH",
    "api gateway": "TECH",
    "service mesh": "TECH",
    "consul": "TECH",
    "istio": "TECH",
    "nginx": "TECH",
    "traefik": "TECH",
    "pgbouncer": "TECH",
    "proxysql": "TECH",
    "ocr": "TECH",
    "nlp": "TECH",
    "phobert": "TECH",
    "transformer": "TECH",
    "llm": "TECH",
    "rag": "TECH",
    "embedding": "TECH",
    "apriori": "TECH",
    "fp-growth": "TECH",
    "xgboost": "TECH",
    "random forest": "TECH",
    "prophet": "TECH",
    "arima": "TECH",
    "collaborative filtering": "TECH",
    "content-based": "TECH",
    "operational transformation": "TECH",
    "crdt": "TECH",
    "optimistic locking": "TECH",
    "two-phase commit": "TECH",
    "saga pattern": "TECH",
    "event sourcing": "TECH",
    "cqrs": "TECH",
    "brotli": "TECH",
    "gzip": "TECH",
    "webp": "TECH",
    "avif": "TECH",

    "hồ sơ nhân sự": "DATA",
    "hồ sơ": "DATA",
    "e-profile": "DATA",
    "lịch sử chấm công": "DATA",
    "bảng chấm công": "DATA",
    "ca làm việc": "DATA",
    "bảng lương": "DATA",
    "phiếu lương": "DATA",
    "đơn nghỉ phép": "DATA",
    "hợp đồng lao động": "DATA",
    "hợp đồng": "DATA",
    "hóa đơn": "DATA",
    "hóa đơn điện tử": "DATA",
    "e-invoice": "DATA",
    "đơn hàng": "DATA",
    "order": "DATA",
    "giỏ hàng": "DATA",
    "cart": "DATA",
    "tồn kho": "DATA",
    "inventory": "DATA",
    "sản phẩm": "DATA",
    "danh mục sản phẩm": "DATA",
    "khách hàng": "DATA",
    "hồ sơ khách hàng": "DATA",
    "lead": "DATA",
    "opportunity": "DATA",
    "ticket": "DATA",
    "vé hỗ trợ": "DATA",
    "log": "DATA",
    "nhật ký": "DATA",
    "audit log": "DATA",
    "session": "DATA",
    "token": "DATA",
    "refresh token": "DATA",
    "access token": "DATA",
    "file": "DATA",
    "tài liệu": "DATA",
    "document": "DATA",
    "hình ảnh": "DATA",
    "video": "DATA",
    "metadata": "DATA",
    "cấu hình": "DATA",
    "setting": "DATA",
    "quyền hạn": "DATA",
    "permission": "DATA",
    "vai trò": "DATA",
    "role": "DATA",
    "thông báo": "DATA",
    "notification": "DATA",
    "báo cáo": "DATA",
    "dashboard data": "DATA",
    "metric": "DATA",
    "chỉ số": "DATA",
    "event": "DATA",
    "sự kiện": "DATA",
    "message": "DATA",
    "tin nhắn": "DATA",
    "review": "DATA",
    "đánh giá": "DATA",
    "rating": "DATA",
    "feedback": "DATA",
    "phản hồi": "DATA",
    "voucher": "DATA",
    "mã giảm giá": "DATA",
    "coupon": "DATA",
    "điểm thưởng": "DATA",
    "loyalty point": "DATA",
    "địa chỉ": "DATA",
    "tọa độ": "DATA",
    "gps": "DATA",
    "device id": "DATA",
    "device fingerprint": "DATA",
    "ip": "DATA",
    "user agent": "DATA",
    "schema": "DATA",
    "migration": "DATA",
    "backup": "DATA",
    "snapshot": "DATA",

    "xác thực": "SECURITY",
    "authentication": "SECURITY",
    "ủy quyền": "SECURITY",
    "authorization": "SECURITY",
    "rbac": "SECURITY",
    "abac": "SECURITY",
    "role-based access control": "SECURITY",
    "attribute-based access control": "SECURITY",
    "mfa": "SECURITY",
    "multi-factor authentication": "SECURITY",
    "2fa": "SECURITY",
    "otp": "SECURITY",
    "biometric authentication": "SECURITY",
    "liveness detection": "SECURITY",
    "device binding": "SECURITY",
    "geofencing": "SECURITY",
    "rate limiting": "SECURITY",
    "throttling": "SECURITY",
    "waf": "SECURITY",
    "web application firewall": "SECURITY",
    "ddos protection": "SECURITY",
    "encryption": "SECURITY",
    "mã hóa": "SECURITY",
    "aes-256": "SECURITY",
    "tls": "SECURITY",
    "ssl": "SECURITY",
    "mtls": "SECURITY",
    "hashing": "SECURITY",
    "salt": "SECURITY",
    "jwt": "SECURITY",
    "token": "SECURITY",
    "refresh token": "SECURITY",
    "api key": "SECURITY",
    "secret": "SECURITY",
    "vault": "SECURITY",
    "kms": "SECURITY",
    "key rotation": "SECURITY",
    "audit log": "SECURITY",
    "immutable log": "SECURITY",
    "worm": "SECURITY",
    "data masking": "SECURITY",
    "data anonymization": "SECURITY",
    "pii": "SECURITY",
    "gdpr": "SECURITY",
    "pci-dss": "SECURITY",
    "zero trust": "SECURITY",
    "least privilege": "SECURITY",
    "input validation": "SECURITY",
    "sql injection": "SECURITY",
    "xss": "SECURITY",
    "csrf": "SECURITY",
    "cors": "SECURITY",
    "content security policy": "SECURITY",
    "secure enclave": "SECURITY",
    "keystore": "SECURITY",
    "certificate": "SECURITY",
    "chứng thư số": "SECURITY",
    "digital signature": "SECURITY",
    "chữ ký số": "SECURITY",
    "timestamp authority": "SECURITY",
    "tsa": "SECURITY",
    "hmac": "SECURITY",
    "ipn": "SECURITY",
    "webhook signature": "SECURITY",

    "quy trình": "PROCESS",
    "workflow": "PROCESS",
    "luồng phê duyệt": "PROCESS",
    "phê duyệt": "PROCESS",
    "duyệt": "PROCESS",
    "onboarding": "PROCESS",
    "offboarding": "PROCESS",
    "tuyển dụng": "PROCESS",
    "tính lương": "PROCESS",
    "chấm công": "PROCESS",
    "đối soát": "PROCESS",
    "reconciliation": "PROCESS",
    "thanh toán": "PROCESS",
    "payment": "PROCESS",
    "hoàn tiền": "PROCESS",
    "refund": "PROCESS",
    "đặt hàng": "PROCESS",
    "order processing": "PROCESS",
    "giao hàng": "PROCESS",
    "shipping": "PROCESS",
    "nhập kho": "PROCESS",
    "xuất kho": "PROCESS",
    "kiểm kê": "PROCESS",
    "inventory check": "PROCESS",
    "backup": "PROCESS",
    "sao lưu": "PROCESS",
    "recovery": "PROCESS",
    "khôi phục": "PROCESS",
    "migration": "PROCESS",
    "deployment": "PROCESS",
    "ci/cd": "PROCESS",
    "rollback": "PROCESS",
    "escalation": "PROCESS",
    "leo thang": "PROCESS",
    "notification": "PROCESS",
    "gửi thông báo": "PROCESS",
    "đồng bộ": "PROCESS",
    "sync": "PROCESS",
    "etl": "PROCESS",
    "data pipeline": "PROCESS",
    "batch processing": "PROCESS",
    "stream processing": "PROCESS",
    "retry": "PROCESS",
    "thử lại": "PROCESS",
    "dead letter queue": "PROCESS",
    "saga": "PROCESS",
    "two-phase commit": "PROCESS",
    "event driven": "PROCESS",
    "event-driven": "PROCESS",

    "real-time": "CONSTRAINT",
    "real time": "CONSTRAINT",
    "thời gian thực": "CONSTRAINT",
    "low latency": "CONSTRAINT",
    "độ trễ thấp": "CONSTRAINT",
    "high availability": "CONSTRAINT",
    "tính sẵn sàng cao": "CONSTRAINT",
    "zero-downtime": "CONSTRAINT",
    "không gián đoạn": "CONSTRAINT",
    "scalability": "CONSTRAINT",
    "khả năng mở rộng": "CONSTRAINT",
    "performance": "CONSTRAINT",
    "hiệu năng": "CONSTRAINT",
    "dưới 100ms": "CONSTRAINT",
    "throughput": "CONSTRAINT",
    "rps": "CONSTRAINT",
    "concurrent": "CONSTRAINT",
    "đồng thời": "CONSTRAINT",
    "secure": "CONSTRAINT",
    "bảo mật cao": "CONSTRAINT",
    "compliance": "CONSTRAINT",
    "tuân thủ": "CONSTRAINT",
    "gdpr": "CONSTRAINT",
    "pci-dss": "CONSTRAINT",
    "auditability": "CONSTRAINT",
    "khả năng kiểm toán": "CONSTRAINT",
    "traceability": "CONSTRAINT",
    "khả năng truy vết": "CONSTRAINT",
    "idempotent": "CONSTRAINT",
    "consistent": "CONSTRAINT",
    "tính nhất quán": "CONSTRAINT",
    "durable": "CONSTRAINT",
    "bền vững": "CONSTRAINT",
    "fault tolerant": "CONSTRAINT",
    "chịu lỗi": "CONSTRAINT",
    "self-healing": "CONSTRAINT",
    "tự phục hồi": "CONSTRAINT",

    "google login": "INTEGRATION",
    "google oauth": "INTEGRATION",
    "facebook login": "INTEGRATION",
    "apple login": "INTEGRATION",
    "vnpay": "INTEGRATION",
    "momo": "INTEGRATION",
    "zalopay": "INTEGRATION",
    "stripe": "INTEGRATION",
    "paypal": "INTEGRATION",
    "ghn": "INTEGRATION",
    "ghtk": "INTEGRATION",
    "viettel post": "INTEGRATION",
    "vietnam post": "INTEGRATION",
    "shopee": "INTEGRATION",
    "lazada": "INTEGRATION",
    "tiki": "INTEGRATION",
    "tiktok shop": "INTEGRATION",
    "facebook shop": "INTEGRATION",
    "firebase": "INTEGRATION",
    "fcm": "INTEGRATION",
    "apns": "INTEGRATION",
    "twilio": "INTEGRATION",
    "sendgrid": "INTEGRATION",
    "mailgun": "INTEGRATION",
    "aws ses": "INTEGRATION",
    "google maps": "INTEGRATION",
    "google maps api": "INTEGRATION",
    "mapbox": "INTEGRATION",
    "openai": "INTEGRATION",
    "claude": "INTEGRATION",
    "telegram bot": "INTEGRATION",
    "zalo oa": "INTEGRATION",
    "zalo zns": "INTEGRATION",
    "whatsapp": "INTEGRATION",
    "slack": "INTEGRATION",
    "microsoft teams": "INTEGRATION",
    "sap": "INTEGRATION",
    "oracle": "INTEGRATION",
    "salesforce": "INTEGRATION",
    "hubspot": "INTEGRATION",
    "active directory": "INTEGRATION",
    "ldap": "INTEGRATION",
    "sso provider": "INTEGRATION",
}

TRIGGER_VERBS = {
    # Intent / Desire
    "muốn": "WANTS_TO",
    "cần": "WANTS_TO",
    "mong muốn": "WANTS_TO",
    "yêu cầu": "WANTS_TO",
    "đề xuất": "WANTS_TO",
    "đề nghị": "WANTS_TO",
    "hy vọng": "WANTS_TO",
    "mong": "WANTS_TO",

    # Develop / Build
    "xây dựng": "DEVELOP",
    "phát triển": "DEVELOP",
    "thiết kế": "DEVELOP",
    "tạo": "DEVELOP",
    "tạo mới": "DEVELOP",
    "xây": "DEVELOP",
    "lập": "DEVELOP",
    "xây dựng mới": "DEVELOP",
    "phát triển mới": "DEVELOP",
    "code": "DEVELOP",
    "lập trình": "DEVELOP",
    "viết": "DEVELOP",
    "xây dựng từ đầu": "DEVELOP",

    # Deploy / Implement
    "triển khai": "DEPLOY",
    "cài đặt": "DEPLOY",
    "cài đặt hệ thống": "DEPLOY",
    "đưa vào sử dụng": "DEPLOY",
    "ra mắt": "DEPLOY",
    "go-live": "DEPLOY",
    "release": "DEPLOY",
    "phát hành": "DEPLOY",
    "triển khai thực tế": "DEPLOY",
    "áp dụng": "DEPLOY",
    "áp dụng vào thực tế": "DEPLOY",

    # Manage / Control
    "quản lý": "MANAGES",
    "quản trị": "MANAGES",
    "điều hành": "MANAGES",
    "kiểm soát": "MANAGES",
    "giám sát": "MANAGES",
    "theo dõi": "MANAGES",
    "monitor": "MANAGES",
    "quản lý và giám sát": "MANAGES",
    "điều phối": "MANAGES",

    # Integrate
    "tích hợp": "INTEGRATES",
    "kết nối": "INTEGRATES",
    "liên kết": "INTEGRATES",
    "đồng bộ": "INTEGRATES",
    "sync": "INTEGRATES",
    "nối": "INTEGRATES",
    "kết hợp": "INTEGRATES",
    "tích hợp với": "INTEGRATES",
    "api integration": "INTEGRATES",

    # Support / Assist
    "hỗ trợ": "SUPPORTS",
    "trợ giúp": "SUPPORTS",
    "giúp": "SUPPORTS",
    "hỗ trợ người dùng": "SUPPORTS",
    "hỗ trợ khách hàng": "SUPPORTS",
    "hỗ trợ vận hành": "SUPPORTS",

    # Process / Handle
    "xử lý": "PROCESSES",
    "xử lý dữ liệu": "PROCESSES",
    "xử lý thông tin": "PROCESSES",
    "xử lý yêu cầu": "PROCESSES",
    "xử lý đơn hàng": "PROCESSES",
    "xử lý quy trình": "PROCESSES",
    "thực hiện": "PROCESSES",
    "thực thi": "PROCESSES",
    "chạy": "PROCESSES",
    "vận hành": "PROCESSES",

    # Automate
    "tự động hóa": "AUTOMATES",
    "tự động": "AUTOMATES",
    "automation": "AUTOMATES",
    "tự động hóa quy trình": "AUTOMATES",
    "tự động hóa công việc": "AUTOMATES",

    # Analyze / Report
    "phân tích": "ANALYZES",
    "phân tích dữ liệu": "ANALYZES",
    "thống kê": "ANALYZES",
    "báo cáo": "REPORTS",
    "tạo báo cáo": "REPORTS",
    "xuất báo cáo": "REPORTS",
    "dashboard": "REPORTS",
    "theo dõi và báo cáo": "REPORTS",

    # Optimize / Improve
    "tối ưu": "OPTIMIZES",
    "tối ưu hóa": "OPTIMIZES",
    "cải thiện": "OPTIMIZES",
    "nâng cao": "OPTIMIZES",
    "cải tiến": "OPTIMIZES",
    "hiệu quả hơn": "OPTIMIZES",
    "giảm chi phí": "OPTIMIZES",
    "tăng hiệu suất": "OPTIMIZES",

    # Search / Query
    "tìm kiếm": "SEARCHES",
    "tra cứu": "SEARCHES",
    "tìm": "SEARCHES",
    "search": "SEARCHES",
    "query": "SEARCHES",
    "lọc": "FILTERS",
    "filter": "FILTERS",

    # Create / Add / Update / Delete (CRUD-ish)
    "thêm": "CREATES",
    "thêm mới": "CREATES",
    "tạo mới": "CREATES",
    "cập nhật": "UPDATES",
    "sửa": "UPDATES",
    "chỉnh sửa": "UPDATES",
    "thay đổi": "UPDATES",
    "xóa": "DELETES",
    "xóa bỏ": "DELETES",
    "loại bỏ": "DELETES",
    "hủy": "DELETES",

    # Approve / Workflow
    "phê duyệt": "APPROVES",
    "duyệt": "APPROVES",
    "xét duyệt": "APPROVES",
    "chấp thuận": "APPROVES",
    "từ chối": "REJECTS",
    "từ chối yêu cầu": "REJECTS",

    # Notify / Alert
    "thông báo": "NOTIFIES",
    "gửi thông báo": "NOTIFIES",
    "cảnh báo": "ALERTS",
    "alert": "ALERTS",
    "gửi email": "NOTIFIES",
    "gửi tin nhắn": "NOTIFIES",

    # Migrate / Convert
    "chuyển đổi": "MIGRATES",
    "migrate": "MIGRATES",
    "di chuyển": "MIGRATES",
    "chuyển dữ liệu": "MIGRATES",
    "chuyển hệ thống": "MIGRATES",
    "nâng cấp": "UPGRADES",
    "upgrade": "UPGRADES",

    # Secure / Protect
    "bảo mật": "SECURITY",
    "bảo vệ": "SECURITY",
    "mã hóa": "SECURITY",
    "phân quyền": "SECURITY",
    "kiểm soát truy cập": "SECURITY",

    # Train / Learn
    "đào tạo": "TRAINS",
    "huấn luyện": "TRAINS",
    "học": "TRAINS",
    "training": "TRAINS",

    # Other common business verbs
    "tính toán": "CALCULATES",
    "tính": "CALCULATES",
    "đánh giá": "EVALUATES",
    "kiểm tra": "CHECKS",
    "kiểm toán": "AUDITS",
    "lưu trữ": "STORES",
    "lưu": "STORES",
    "backup": "BACKUPS",
    "sao lưu": "BACKUPS",
    "khôi phục": "RECOVERS",
    "restore": "RECOVERS",

    # ====================== ANALYZE / REPORT ======================
    "phân tích": "ANALYZES",
    "phân tích dữ liệu": "ANALYZES",
    "thống kê": "ANALYZES",
    "báo cáo": "REPORTS",
    "tạo báo cáo": "REPORTS",
    "xuất báo cáo": "REPORTS",
    "dashboard": "REPORTS",
    "theo dõi và báo cáo": "REPORTS",
    "giám sát": "MONITORS",
    "theo dõi": "MONITORS",
    "monitor": "MONITORS",
    "tracking": "MONITORS",
    "ghi nhận": "LOGS",
    "ghi log": "LOGS",
    "logging": "LOGS",

    # ====================== OPTIMIZE / IMPROVE ======================
    "tối ưu": "OPTIMIZES",
    "tối ưu hóa": "OPTIMIZES",
    "cải thiện": "OPTIMIZES",
    "nâng cao": "OPTIMIZES",
    "cải tiến": "OPTIMIZES",
    "hiệu quả hơn": "OPTIMIZES",
    "giảm chi phí": "OPTIMIZES",
    "tăng hiệu suất": "OPTIMIZES",
    "tăng tốc": "OPTIMIZES",
    "giảm độ trễ": "OPTIMIZES",

    # ====================== SEARCH / FILTER ======================
    "tìm kiếm": "SEARCHES",
    "tra cứu": "SEARCHES",
    "tìm": "SEARCHES",
    "search": "SEARCHES",
    "query": "SEARCHES",
    "lọc": "FILTERS",
    "filter": "FILTERS",
    "gợi ý": "RECOMMENDS",
    "đề xuất": "RECOMMENDS",
    "recommend": "RECOMMENDS",
    "autocomplete": "SUGGESTS",
    "gợi ý từ khóa": "SUGGESTS",

    # ====================== CRUD ======================
    "thêm": "CREATES",
    "thêm mới": "CREATES",
    "tạo mới": "CREATES",
    "tạo": "CREATES",
    "khởi tạo": "CREATES",
    "generate": "CREATES",
    "sinh": "CREATES",
    "cập nhật": "UPDATES",
    "sửa": "UPDATES",
    "chỉnh sửa": "UPDATES",
    "thay đổi": "UPDATES",
    "cập nhật trạng thái": "UPDATES",
    "xóa": "DELETES",
    "xóa bỏ": "DELETES",
    "loại bỏ": "DELETES",
    "hủy": "DELETES",
    "xóa vĩnh viễn": "DELETES",

    # ====================== APPROVE / WORKFLOW ======================
    "phê duyệt": "APPROVES",
    "duyệt": "APPROVES",
    "xét duyệt": "APPROVES",
    "chấp thuận": "APPROVES",
    "từ chối": "REJECTS",
    "từ chối yêu cầu": "REJECTS",
    "leo thang": "ESCALATES",
    "escalate": "ESCALATES",
    "chuyển cấp": "ESCALATES",

    # ====================== NOTIFY / ALERT ======================
    "thông báo": "NOTIFIES",
    "gửi thông báo": "NOTIFIES",
    "cảnh báo": "ALERTS",
    "alert": "ALERTS",
    "gửi email": "NOTIFIES",
    "gửi tin nhắn": "NOTIFIES",
    "gửi sms": "NOTIFIES",
    "push notification": "NOTIFIES",
    "gửi cảnh báo": "ALERTS",

    # ====================== MIGRATE / UPGRADE ======================
    "chuyển đổi": "MIGRATES",
    "migrate": "MIGRATES",
    "di chuyển": "MIGRATES",
    "chuyển dữ liệu": "MIGRATES",
    "chuyển hệ thống": "MIGRATES",
    "nâng cấp": "UPGRADES",
    "upgrade": "UPGRADES",
    "cập nhật phiên bản": "UPGRADES",

    # ====================== SECURE / PROTECT ======================
    "bảo mật": "SECURITY",
    "bảo vệ": "SECURITY",
    "mã hóa": "ENCRYPTS",
    "phân quyền": "AUTHORIZES",
    "kiểm soát truy cập": "AUTHORIZES",
    "xác thực": "AUTHENTICATES",
    "authentication": "AUTHENTICATES",
    "ủy quyền": "AUTHORIZES",
    "authorization": "AUTHORIZES",
    "chống": "PROTECTS_AGAINST",
    "ngăn chặn": "PROTECTS_AGAINST",
    "phát hiện": "DETECTS",
    "detect": "DETECTS",

    # ====================== TRAIN / LEARN ======================
    "đào tạo": "TRAINS",
    "huấn luyện": "TRAINS",
    "học": "TRAINS",
    "training": "TRAINS",
    "fine-tune": "TRAINS",
    "huấn luyện model": "TRAINS",

    # ====================== CALCULATE / EVALUATE / CHECK ======================
    "tính toán": "CALCULATES",
    "tính": "CALCULATES",
    "đánh giá": "EVALUATES",
    "kiểm tra": "CHECKS",
    "validate": "VALIDATES",
    "xác minh": "VALIDATES",
    "kiểm toán": "AUDITS",
    "audit": "AUDITS",
    "đối soát": "RECONCILES",
    "reconcile": "RECONCILES",

    # ====================== STORE / BACKUP / RECOVER ======================
    "lưu trữ": "STORES",
    "lưu": "STORES",
    "ghi": "STORES",
    "persist": "STORES",
    "backup": "BACKUPS",
    "sao lưu": "BACKUPS",
    "khôi phục": "RECOVERS",
    "restore": "RECOVERS",
    "phục hồi": "RECOVERS",

    # ====================== USE / APPLY / INTEGRATE (Rất quan trọng) ======================
    "sử dụng": "USES",
    "dùng": "USES",
    "áp dụng": "APPLIES",
    "ứng dụng": "APPLIES",
    "tích hợp": "INTEGRATES_WITH",
    "kết hợp": "INTEGRATES_WITH",
    "kết nối": "CONNECTS_TO",
    "gọi": "CALLS",
    "call": "CALLS",
    "invoke": "CALLS",

    # ====================== DEPEND / TRIGGER / SEND ======================
    "phụ thuộc": "DEPENDS_ON",
    "dựa trên": "BASED_ON",
    "dựa vào": "BASED_ON",
    "kích hoạt": "TRIGGERS",
    "trigger": "TRIGGERS",
    "gửi": "SENDS",
    "nhận": "RECEIVES",
    "đẩy": "PUSHES",
    "kéo": "PULLS",

    # ====================== DISPLAY / SHOW / RENDER ======================
    "hiển thị": "DISPLAYS",
    "show": "DISPLAYS",
    "render": "RENDERS",
    "vẽ": "RENDERS",
    "trực quan hóa": "VISUALIZES",
    "visualize": "VISUALIZES",

    # ====================== SYNC / PROCESS ======================
    "đồng bộ": "SYNCHRONIZES",
    "sync": "SYNCHRONIZES",
    "xử lý": "PROCESSES",
    "process": "PROCESSES",
    "xử lý ngầm": "PROCESSES",
    "background": "PROCESSES",
    "batch": "PROCESSES",
    "stream": "PROCESSES",

    # ====================== CONFIGURE / DEPLOY ======================
    "cấu hình": "CONFIGURES",
    "config": "CONFIGURES",
    "thiết lập": "CONFIGURES",
    "triển khai": "DEPLOYS",
    "deploy": "DEPLOYS",
    "đóng gói": "PACKAGES",
    "build": "BUILDS",
    "compile": "BUILDS",

    # ====================== SUPPORT / ENABLE ======================
    "hỗ trợ": "SUPPORTS",
    "support": "SUPPORTS",
    "cho phép": "ENABLES",
    "enable": "ENABLES",
    "cung cấp": "PROVIDES",
    "provide": "PROVIDES",

    # ====================== GENERATE / EXPORT / IMPORT ======================
    "xuất": "EXPORTS",
    "export": "EXPORTS",
    "nhập": "IMPORTS",
    "import": "IMPORTS",
    "tải lên": "UPLOADS",
    "upload": "UPLOADS",
    "tải xuống": "DOWNLOADS",
    "download": "DOWNLOADS",

    # ====================== SCHEDULE / AUTOMATE ======================
    "lên lịch": "SCHEDULES",
    "schedule": "SCHEDULES",
    "tự động": "AUTOMATES",
    "tự động hóa": "AUTOMATES",
    "automation": "AUTOMATES",
}

RELATION_RULES = {
    # =========================================================
    # ORG → *
    # =========================================================
    ("ORG", "SYS"): {
        "default": "WANTS_TO_DEVELOP",
        "triggers": {
            "muốn": "WANTS_TO_DEVELOP",
            "cần": "WANTS_TO_DEVELOP",
            "mong muốn": "WANTS_TO_DEVELOP",
            "yêu cầu": "WANTS_TO_DEVELOP",
            "xây dựng": "DEVELOP",
            "phát triển": "DEVELOP",
            "thiết kế": "DEVELOP",
            "tạo": "DEVELOP",
            "triển khai": "DEPLOY",
            "cài đặt": "DEPLOY",
            "sử dụng": "USES",
            "vận hành": "OPERATES",
            "quản lý": "MANAGES",
            "quản trị": "ADMINISTERS",
            "tích hợp": "INTEGRATES_WITH",
            "kết nối": "CONNECTS_TO",
            "nâng cấp": "UPGRADES",
            "migrate": "MIGRATES_TO",
            "chuyển đổi": "MIGRATES_TO",
            "hỗ trợ": "SUPPORTS",
        }
    },
    ("ORG", "FEATURE"): {
        "default": "WANTS_FEATURE",
        "triggers": {
            "muốn": "WANTS_FEATURE",
            "cần": "NEEDS_FEATURE",
            "yêu cầu": "NEEDS_FEATURE",
            "quản lý": "MANAGES_FEATURE",
            "sử dụng": "USES_FEATURE",
            "theo dõi": "TRACKS_FEATURE",
            "báo cáo": "REPORTS_ON",
            "phân tích": "ANALYZES_FEATURE",
            "tối ưu": "OPTIMIZES_FEATURE",
            "cải thiện": "IMPROVES_FEATURE",
            "phê duyệt": "APPROVES",
            "thực hiện": "PERFORMS",
        }
    },
    ("ORG", "TECH"): {
        "default": "USES",
        "triggers": {
            "sử dụng": "USES",
            "áp dụng": "APPLIES",
            "dùng": "USES",
            "triển khai": "DEPLOYS",
            "tích hợp": "INTEGRATES",
            "dựa trên": "BASED_ON",
        }
    },
    ("ORG", "DATA"): {
        "default": "MANAGES",
        "triggers": {
            "quản lý": "MANAGES",
            "sở hữu": "OWNS",
            "truy cập": "ACCESSES",
            "xem": "VIEWS",
            "cập nhật": "UPDATES",
            "xóa": "DELETES",
            "nhập": "IMPORTS",
            "xuất": "EXPORTS",
        }
    },
    ("ORG", "SECURITY"): {
        "default": "REQUIRES",
        "triggers": {
            "yêu cầu": "REQUIRES",
            "cần": "REQUIRES",
            "áp dụng": "APPLIES",
            "sử dụng": "USES",
            "triển khai": "IMPLEMENTS",
        }
    },
    ("ORG", "PROCESS"): {
        "default": "PERFORMS",
        "triggers": {
            "thực hiện": "PERFORMS",
            "tham gia": "PARTICIPATES_IN",
            "quản lý": "MANAGES",
            "phê duyệt": "APPROVES",
            "theo dõi": "MONITORS",
            "tự động hóa": "AUTOMATES",
        }
    },
    ("ORG", "CONSTRAINT"): {
        "default": "REQUIRES",
        "triggers": {
            "yêu cầu": "REQUIRES",
            "cần": "REQUIRES",
            "đảm bảo": "REQUIRES",
            "tuân thủ": "COMPLIES_WITH",
        }
    },
    ("ORG", "INTEGRATION"): {
        "default": "USES",
        "triggers": {
            "tích hợp": "INTEGRATES_WITH",
            "kết nối": "CONNECTS_TO",
            "sử dụng": "USES",
            "gọi": "CALLS",
        }
    },
    ("ORG", "ORG"): {
        "default": "ASSOCIATED_WITH",
        "triggers": {
            "hỗ trợ": "SUPPORTS",
            "hợp tác": "COLLABORATES_WITH",
            "cung cấp": "SUPPLIES",
            "mua": "BUYS_FROM",
            "bán": "SELLS_TO",
            "phục vụ": "SERVES",
            "quản lý": "MANAGES",
            "báo cáo cho": "REPORTS_TO",
            "thuộc": "BELONGS_TO",
            "là đối tác của": "PARTNERS_WITH",
            "cạnh tranh với": "COMPETES_WITH",
        }
    },

    # =========================================================
    # SYS → *
    # =========================================================
    ("SYS", "FEATURE"): {
        "default": "HAS_FEATURE",
        "triggers": {
            "quản lý": "MANAGES",
            "tích hợp": "INTEGRATES",
            "xử lý": "PROCESSES",
            "tự động hóa": "AUTOMATES",
            "hỗ trợ": "SUPPORTS",
            "cung cấp": "PROVIDES",
            "báo cáo": "REPORTS",
            "phân tích": "ANALYZES",
            "theo dõi": "MONITORS",
            "giám sát": "MONITORS",
            "tạo": "CREATES",
            "lưu trữ": "STORES",
            "tìm kiếm": "SEARCHES",
            "lọc": "FILTERS",
            "phê duyệt": "APPROVES",
            "thông báo": "NOTIFIES",
            "tính toán": "CALCULATES",
            "tối ưu": "OPTIMIZES",
            "xuất": "EXPORTS",
            "nhập": "IMPORTS",
        }
    },
    ("SYS", "TECH"): {
        "default": "USES",
        "triggers": {
            "sử dụng": "USES",
            "dùng": "USES",
            "áp dụng": "APPLIES",
            "ứng dụng": "APPLIES",
            "dựa trên": "BASED_ON",
            "xây dựng trên": "BUILT_ON",
            "triển khai bằng": "IMPLEMENTED_WITH",
            "tích hợp": "INTEGRATES",
            "kết hợp": "COMBINES_WITH",
        }
    },
    ("SYS", "DATA"): {
        "default": "STORES",
        "triggers": {
            "lưu trữ": "STORES",
            "lưu": "STORES",
            "ghi": "STORES",
            "quản lý": "MANAGES",
            "xử lý": "PROCESSES",
            "đồng bộ": "SYNCHRONIZES",
            "sao lưu": "BACKS_UP",
            "khôi phục": "RECOVERS",
            "mã hóa": "ENCRYPTS",
            "ẩn danh hóa": "ANONYMIZES",
        }
    },
    ("SYS", "SECURITY"): {
        "default": "IMPLEMENTS",
        "triggers": {
            "áp dụng": "IMPLEMENTS",
            "sử dụng": "USES",
            "triển khai": "IMPLEMENTS",
            "tích hợp": "INTEGRATES",
            "bảo vệ bằng": "PROTECTS_WITH",
            "xác thực bằng": "AUTHENTICATES_WITH",
            "mã hóa bằng": "ENCRYPTS_WITH",
            "phân quyền": "AUTHORIZES",
        }
    },
    ("SYS", "PROCESS"): {
        "default": "EXECUTES",
        "triggers": {
            "thực thi": "EXECUTES",
            "chạy": "RUNS",
            "xử lý": "PROCESSES",
            "tự động hóa": "AUTOMATES",
            "hỗ trợ": "SUPPORTS",
            "quản lý": "MANAGES",
            "theo dõi": "MONITORS",
        }
    },
    ("SYS", "CONSTRAINT"): {
        "default": "MUST_SATISFY",
        "triggers": {
            "đảm bảo": "MUST_SATISFY",
            "yêu cầu": "REQUIRES",
            "cần": "REQUIRES",
            "tuân thủ": "COMPLIES_WITH",
            "đạt": "ACHIEVES",
            "hỗ trợ": "SUPPORTS",
        }
    },
    ("SYS", "INTEGRATION"): {
        "default": "INTEGRATES_WITH",
        "triggers": {
            "tích hợp": "INTEGRATES_WITH",
            "kết nối": "CONNECTS_TO",
            "gọi": "CALLS",
            "sử dụng": "USES",
            "đồng bộ với": "SYNCS_WITH",
        }
    },
    ("SYS", "SYS"): {
        "default": "INTEGRATES_WITH",
        "triggers": {
            "tích hợp": "INTEGRATES_WITH",
            "kết nối": "CONNECTS_TO",
            "đồng bộ": "SYNCS_WITH",
            "liên kết": "LINKS_TO",
            "gọi": "CALLS",
            "sử dụng": "USES",
            "phụ thuộc": "DEPENDS_ON",
            "thay thế": "REPLACES",
            "nâng cấp từ": "UPGRADES_FROM",
            "migrate từ": "MIGRATES_FROM",
        }
    },
    ("SYS", "ORG"): {
        "default": "USED_BY",
        "triggers": {
            "phục vụ": "SERVES",
            "hỗ trợ": "SUPPORTS",
            "dành cho": "DESIGNED_FOR",
            "sử dụng bởi": "USED_BY",
            "quản lý bởi": "MANAGED_BY",
        }
    },

    # =========================================================
    # FEATURE → *
    # =========================================================
    ("FEATURE", "TECH"): {
        "default": "USES",
        "triggers": {
            "sử dụng": "USES",
            "áp dụng": "APPLIES",
            "dùng": "USES",
            "dựa trên": "BASED_ON",
            "ứng dụng": "APPLIES",
            "kết hợp": "COMBINES_WITH",
            "tích hợp": "INTEGRATES",
        }
    },
    ("FEATURE", "DATA"): {
        "default": "PROCESSES",
        "triggers": {
            "xử lý": "PROCESSES",
            "quản lý": "MANAGES",
            "tạo": "CREATES",
            "cập nhật": "UPDATES",
            "xóa": "DELETES",
            "lưu": "STORES",
            "phân tích": "ANALYZES",
            "báo cáo": "REPORTS_ON",
            "tìm kiếm": "SEARCHES",
            "lọc": "FILTERS",
            "xuất": "EXPORTS",
            "nhập": "IMPORTS",
        }
    },
    ("FEATURE", "SECURITY"): {
        "default": "REQUIRES",
        "triggers": {
            "yêu cầu": "REQUIRES",
            "cần": "REQUIRES",
            "sử dụng": "USES",
            "áp dụng": "APPLIES",
            "bảo vệ bằng": "PROTECTED_BY",
            "xác thực": "AUTHENTICATES",
            "phân quyền": "AUTHORIZES",
        }
    },
    ("FEATURE", "PROCESS"): {
        "default": "INVOLVES",
        "triggers": {
            "bao gồm": "INVOLVES",
            "thực hiện": "PERFORMS",
            "tự động hóa": "AUTOMATES",
            "hỗ trợ": "SUPPORTS",
            "quản lý": "MANAGES",
        }
    },
    ("FEATURE", "CONSTRAINT"): {
        "default": "MUST_SATISFY",
        "triggers": {
            "đảm bảo": "MUST_SATISFY",
            "yêu cầu": "REQUIRES",
            "cần": "REQUIRES",
            "tuân thủ": "COMPLIES_WITH",
            "hỗ trợ": "SUPPORTS",
            "đạt": "ACHIEVES",
        }
    },
    ("FEATURE", "INTEGRATION"): {
        "default": "USES",
        "triggers": {
            "tích hợp": "INTEGRATES_WITH",
            "sử dụng": "USES",
            "kết nối": "CONNECTS_TO",
            "gọi": "CALLS",
        }
    },
    ("FEATURE", "FEATURE"): {
        "default": "RELATED_TO",
        "triggers": {
            "liên quan": "RELATED_TO",
            "dựa trên": "BASED_ON",
            "phụ thuộc": "DEPENDS_ON",
            "tạo ra": "GENERATES",
            "sử dụng": "USES",
            "kết hợp": "COMBINES_WITH",
            "tối ưu": "OPTIMIZES",
        }
    },
    ("FEATURE", "SYS"): {
        "default": "IMPLEMENTED_IN",
        "triggers": {
            "trong": "IMPLEMENTED_IN",
            "của": "PART_OF",
            "thuộc": "BELONGS_TO",
            "được hỗ trợ bởi": "SUPPORTED_BY",
        }
    },
    ("FEATURE", "ORG"): {
        "default": "USED_BY",
        "triggers": {
            "dành cho": "DESIGNED_FOR",
            "phục vụ": "SERVES",
            "sử dụng bởi": "USED_BY",
            "quản lý bởi": "MANAGED_BY",
        }
    },

    # =========================================================
    # TECH → *
    # =========================================================
    ("TECH", "SYS"): {
        "default": "USED_IN",
        "triggers": {
            "trong": "USED_IN",
            "của": "PART_OF",
            "hỗ trợ": "SUPPORTS",
            "được sử dụng bởi": "USED_BY",
        }
    },
    ("TECH", "FEATURE"): {
        "default": "ENABLES",
        "triggers": {
            "hỗ trợ": "ENABLES",
            "cho phép": "ENABLES",
            "phục vụ": "SUPPORTS",
            "dùng cho": "USED_FOR",
        }
    },
    ("TECH", "TECH"): {
        "default": "RELATED_TO",
        "triggers": {
            "kết hợp": "COMBINES_WITH",
            "sử dụng cùng": "USED_WITH",
            "phụ thuộc": "DEPENDS_ON",
            "thay thế": "REPLACES",
            "tương thích": "COMPATIBLE_WITH",
        }
    },
    ("TECH", "DATA"): {
        "default": "PROCESSES",
        "triggers": {
            "xử lý": "PROCESSES",
            "lưu trữ": "STORES",
            "mã hóa": "ENCRYPTS",
            "truy vấn": "QUERIES",
        }
    },
    ("TECH", "SECURITY"): {
        "default": "IMPLEMENTS",
        "triggers": {
            "thực hiện": "IMPLEMENTS",
            "hỗ trợ": "SUPPORTS",
            "cung cấp": "PROVIDES",
        }
    },

    # =========================================================
    # DATA → *
    # =========================================================
    ("DATA", "SYS"): {
        "default": "STORED_IN",
        "triggers": {
            "trong": "STORED_IN",
            "lưu tại": "STORED_IN",
            "thuộc": "BELONGS_TO",
            "được quản lý bởi": "MANAGED_BY",
        }
    },
    ("DATA", "FEATURE"): {
        "default": "USED_BY",
        "triggers": {
            "dùng cho": "USED_BY",
            "phục vụ": "SERVES",
            "cung cấp cho": "PROVIDES_TO",
        }
    },
    ("DATA", "DATA"): {
        "default": "RELATED_TO",
        "triggers": {
            "liên quan": "RELATED_TO",
            "tham chiếu": "REFERENCES",
            "chứa": "CONTAINS",
            "bao gồm": "CONTAINS",
            "được tạo từ": "DERIVED_FROM",
        }
    },
    ("DATA", "SECURITY"): {
        "default": "PROTECTED_BY",
        "triggers": {
            "được bảo vệ bởi": "PROTECTED_BY",
            "mã hóa bởi": "ENCRYPTED_BY",
            "ẩn danh hóa": "ANONYMIZED_BY",
        }
    },

    # =========================================================
    # SECURITY → *
    # =========================================================
    ("SECURITY", "SYS"): {
        "default": "PROTECTS",
        "triggers": {
            "bảo vệ": "PROTECTS",
            "bảo mật cho": "SECURITY",
            "áp dụng cho": "APPLIED_TO",
        }
    },
    ("SECURITY", "FEATURE"): {
        "default": "PROTECTS",
        "triggers": {
            "bảo vệ": "PROTECTS",
            "bảo mật": "SECURITY",
            "kiểm soát": "CONTROLS",
        }
    },
    ("SECURITY", "DATA"): {
        "default": "PROTECTS",
        "triggers": {
            "bảo vệ": "PROTECTS",
            "mã hóa": "ENCRYPTS",
            "ẩn danh hóa": "ANONYMIZES",
            "masking": "MASKS",
        }
    },
    ("SECURITY", "SECURITY"): {
        "default": "COMPLEMENTS",
        "triggers": {
            "kết hợp": "COMBINES_WITH",
            "bổ sung": "COMPLEMENTS",
            "phụ thuộc": "DEPENDS_ON",
        }
    },

    # =========================================================
    # PROCESS → *
    # =========================================================
    ("PROCESS", "SYS"): {
        "default": "RUNS_ON",
        "triggers": {
            "trên": "RUNS_ON",
            "trong": "RUNS_IN",
            "được thực thi bởi": "EXECUTED_BY",
        }
    },
    ("PROCESS", "FEATURE"): {
        "default": "SUPPORTS",
        "triggers": {
            "hỗ trợ": "SUPPORTS",
            "phục vụ": "SERVES",
            "tạo ra": "GENERATES",
        }
    },
    ("PROCESS", "PROCESS"): {
        "default": "RELATED_TO",
        "triggers": {
            "trước": "PRECEDES",
            "sau": "FOLLOWS",
            "kích hoạt": "TRIGGERS",
            "phụ thuộc": "DEPENDS_ON",
            "bao gồm": "INCLUDES",
        }
    },
    ("PROCESS", "DATA"): {
        "default": "PROCESSES",
        "triggers": {
            "xử lý": "PROCESSES",
            "tạo": "CREATES",
            "cập nhật": "UPDATES",
            "đọc": "READS",
        }
    },

    # =========================================================
    # CONSTRAINT → *
    # =========================================================
    ("CONSTRAINT", "SYS"): {
        "default": "APPLIES_TO",
        "triggers": {
            "áp dụng cho": "APPLIES_TO",
            "yêu cầu đối với": "REQUIRED_FOR",
        }
    },
    ("CONSTRAINT", "FEATURE"): {
        "default": "APPLIES_TO",
        "triggers": {
            "áp dụng cho": "APPLIES_TO",
            "yêu cầu đối với": "REQUIRED_FOR",
        }
    },

    # =========================================================
    # INTEGRATION → *
    # =========================================================
    ("INTEGRATION", "SYS"): {
        "default": "INTEGRATED_INTO",
        "triggers": {
            "được tích hợp vào": "INTEGRATED_INTO",
            "kết nối với": "CONNECTS_TO",
        }
    },
    ("INTEGRATION", "FEATURE"): {
        "default": "ENABLES",
        "triggers": {
            "hỗ trợ": "ENABLES",
            "cho phép": "ENABLES",
            "phục vụ": "SUPPORTS",
        }
    },
}
