from enum import Enum

class Tag(Enum):
    AIML        = "aiml"
    CATEGORY    = "category"
    PATTERN     = "pattern"
    TEMPLATE    = "template"
    THAT        = "that"
    THINK       = "think"
    SET         = "set"
    GET         = "get"
    STAR        = "star"
    SRAI        = "srai"

ENTITY_MAP = {
    # ORG (Organizations / Roles)
    "công ty": "ORG",
    "đơn vị": "ORG",
    "đơn vị bạn": "ORG",
    "khách hàng": "ORG",
    "đối tác": "ORG",
    "doanh nghiệp": "ORG",
    "tổ chức": "ORG",
    "phòng ban": "ORG",
    "bộ phận": "ORG",
    "chi nhánh": "ORG",
    "cơ quan": "ORG",
    "cơ quan nhà nước": "ORG",
    "cơ quan quản lý": "ORG",
    "ban lãnh đạo": "ORG",
    "hội đồng quản trị": "ORG",
    "nhà cung cấp": "ORG",
    "đối thủ cạnh tranh": "ORG",
    "nhà đầu tư": "ORG",
    "cổ đông": "ORG",
    "nhân viên": "ORG",
    "cán bộ": "ORG",
    "lãnh đạo": "ORG",
    "quản lý cấp cao": "ORG",
    "trưởng phòng": "ORG",
    "giám đốc": "ORG",
    "ceo": "ORG",
    "cto": "ORG",
    "cfo": "ORG",
    "team": "ORG",
    "nhóm": "ORG",
    "đội ngũ": "ORG",
    "user": "ORG",
    "người dùng": "ORG",
    "end user": "ORG",
    "admin": "ORG",
    "quản trị viên": "ORG",
    "khách hàng nội bộ": "ORG",
    "khách hàng bên ngoài": "ORG",

    # SYS (Systems / Software / Infrastructure)
    "ứng dụng": "SYS",
    "hệ thống": "SYS",
    "nền tảng": "SYS",
    "hạ tầng mạng": "SYS",
    "phần mềm": "SYS",
    "software": "SYS",
    "hệ thống thông tin": "SYS",
    "hệ thống quản lý": "SYS",
    "erp": "SYS",
    "crm": "SYS",
    "hrm": "SYS",
    "hrms": "SYS",
    "lms": "SYS",
    "cms": "SYS",
    "dms": "SYS",
    "bpm": "SYS",
    "workflow": "SYS",
    "portal": "SYS",
    "cổng thông tin": "SYS",
    "website": "SYS",
    "web app": "SYS",
    "mobile app": "SYS",
    "ứng dụng di động": "SYS",
    "app": "SYS",
    "api": "SYS",
    "microservices": "SYS",
    "dịch vụ": "SYS",
    "service": "SYS",
    "server": "SYS",
    "máy chủ": "SYS",
    "cloud": "SYS",
    "điện toán đám mây": "SYS",
    "aws": "SYS",
    "azure": "SYS",
    "google cloud": "SYS",
    "database": "SYS",
    "cơ sở dữ liệu": "SYS",
    "db": "SYS",
    "sql": "SYS",
    "nosql": "SYS",
    "data warehouse": "SYS",
    "kho dữ liệu": "SYS",
    "data lake": "SYS",
    "hạ tầng": "SYS",
    "infrastructure": "SYS",
    "mạng": "SYS",
    "network": "SYS",
    "firewall": "SYS",
    "bảo mật": "SYS",
    "security": "SYS",
    "authentication": "SYS",
    "authorization": "SYS",
    "đăng nhập": "SYS",
    "sso": "SYS",
    "ldap": "SYS",
    "active directory": "SYS",
    "ci/cd": "SYS",
    "devops": "SYS",
    "container": "SYS",
    "docker": "SYS",
    "kubernetes": "SYS",
    "k8s": "SYS",
    "message queue": "SYS",
    "kafka": "SYS",
    "rabbitmq": "SYS",
    "cache": "SYS",
    "redis": "SYS",
    "load balancer": "SYS",
    "cdn": "SYS",
    "monitoring": "SYS",
    "logging": "SYS",
    "backup": "SYS",
    "sao lưu": "SYS",
    "recovery": "SYS",
    "khôi phục": "SYS",

    # FEATURE (Business features / Outputs)
    "nhân sự": "FEATURE",
    "quản lý": "FEATURE",
    "quy trình": "FEATURE",
    "tự động hóa": "FEATURE",
    "báo cáo": "FEATURE",
    "tài liệu": "FEATURE",
    "thông tin": "FEATURE",
    "dữ liệu": "FEATURE",
    "thời gian thực": "FEATURE",
    "chi phí": "FEATURE",
    "lương": "FEATURE",
    "chấm công": "FEATURE",
    "tuyển dụng": "FEATURE",
    "đào tạo": "FEATURE",
    "đánh giá": "FEATURE",
    "kpi": "FEATURE",
    "hiệu suất": "FEATURE",
    "năng suất": "FEATURE",
    "doanh thu": "FEATURE",
    "lợi nhuận": "FEATURE",
    "doanh số": "FEATURE",
    "bán hàng": "FEATURE",
    "marketing": "FEATURE",
    "quảng cáo": "FEATURE",
    "khuyến mãi": "FEATURE",
    "sản phẩm": "FEATURE",
    "dịch vụ": "FEATURE",
    "đơn hàng": "FEATURE",
    "hóa đơn": "FEATURE",
    "thanh toán": "FEATURE",
    "giao hàng": "FEATURE",
    "kho": "FEATURE",
    "tồn kho": "FEATURE",
    "nhập kho": "FEATURE",
    "xuất kho": "FEATURE",
    "mua hàng": "FEATURE",
    "cung ứng": "FEATURE",
    "chuỗi cung ứng": "FEATURE",
    "sản xuất": "FEATURE",
    "vận hành": "FEATURE",
    "vận chuyển": "FEATURE",
    "logistics": "FEATURE",
    "khách hàng tiềm năng": "FEATURE",
    "lead": "FEATURE",
    "cơ hội bán hàng": "FEATURE",
    "opportunity": "FEATURE",
    "hợp đồng": "FEATURE",
    "thỏa thuận": "FEATURE",
    "dự án": "FEATURE",
    "task": "FEATURE",
    "công việc": "FEATURE",
    "ticket": "FEATURE",
    "yêu cầu": "FEATURE",
    "phản hồi": "FEATURE",
    "feedback": "FEATURE",
    "khiếu nại": "FEATURE",
    "hỗ trợ": "FEATURE",
    "support": "FEATURE",
    "dashboard": "FEATURE",
    "biểu đồ": "FEATURE",
    "thống kê": "FEATURE",
    "phân tích": "FEATURE",
    "analytics": "FEATURE",
    "báo cáo tài chính": "FEATURE",
    "báo cáo doanh thu": "FEATURE",
    "báo cáo nhân sự": "FEATURE",
    "export": "FEATURE",
    "xuất file": "FEATURE",
    "import": "FEATURE",
    "nhập dữ liệu": "FEATURE",
    "đồng bộ": "FEATURE",
    "sync": "FEATURE",
    "thông báo": "FEATURE",
    "notification": "FEATURE",
    "email": "FEATURE",
    "sms": "FEATURE",
    "push notification": "FEATURE",
    "phân quyền": "FEATURE",
    "role": "FEATURE",
    "permission": "FEATURE",
    "audit log": "FEATURE",
    "nhật ký": "FEATURE",
    "lịch sử": "FEATURE",
    "version": "FEATURE",
    "phiên bản": "FEATURE",
    "workflow approval": "FEATURE",
    "phê duyệt": "FEATURE",
    "duyệt": "FEATURE",
    "tự động": "FEATURE",
    "automation": "FEATURE",
    "rule": "FEATURE",
    "quy tắc": "FEATURE",
    "cấu hình": "FEATURE",
    "setting": "FEATURE",
    "tùy chỉnh": "FEATURE",
    "customization": "FEATURE",
    "template": "FEATURE",
    "mẫu": "FEATURE",
    "form": "FEATURE",
    "biểu mẫu": "FEATURE",
    "search": "FEATURE",
    "tìm kiếm": "FEATURE",
    "filter": "FEATURE",
    "lọc": "FEATURE",
    "sort": "FEATURE",
    "sắp xếp": "FEATURE",
    "pagination": "FEATURE",
    "phân trang": "FEATURE",
    "upload": "FEATURE",
    "tải lên": "FEATURE",
    "download": "FEATURE",
    "tải xuống": "FEATURE",
    "preview": "FEATURE",
    "xem trước": "FEATURE",
    "print": "FEATURE",
    "in ấn": "FEATURE",
    "chi phí vận hành": "FEATURE",
    "chi phí nhân sự": "FEATURE",
    "roi": "FEATURE",
    "hiệu quả": "FEATURE",
    "tối ưu": "FEATURE",
    "optimization": "FEATURE",
}

TRIGGER_VERBS = {
    # Intent / Desire
    "muốn": "WANTS_TO",
    "cần": "WANTS_TO",
    "mong muốn": "WANTS_TO",
    "yêu cầu": "WANTS_TO",
    "đề xuất": "WANTS_TO",
    "đề nghị": "WANTS_TO",
    "hy vọng": "WANTS_TO",
    "mong": "WANTS_TO",

    # Develop / Build
    "xây dựng": "DEVELOP",
    "phát triển": "DEVELOP",
    "thiết kế": "DEVELOP",
    "tạo": "DEVELOP",
    "tạo mới": "DEVELOP",
    "xây": "DEVELOP",
    "lập": "DEVELOP",
    "xây dựng mới": "DEVELOP",
    "phát triển mới": "DEVELOP",
    "code": "DEVELOP",
    "lập trình": "DEVELOP",
    "viết": "DEVELOP",
    "xây dựng từ đầu": "DEVELOP",

    # Deploy / Implement
    "triển khai": "DEPLOY",
    "cài đặt": "DEPLOY",
    "cài đặt hệ thống": "DEPLOY",
    "đưa vào sử dụng": "DEPLOY",
    "ra mắt": "DEPLOY",
    "go-live": "DEPLOY",
    "release": "DEPLOY",
    "phát hành": "DEPLOY",
    "triển khai thực tế": "DEPLOY",
    "áp dụng": "DEPLOY",
    "áp dụng vào thực tế": "DEPLOY",

    # Manage / Control
    "quản lý": "MANAGES",
    "quản trị": "MANAGES",
    "điều hành": "MANAGES",
    "kiểm soát": "MANAGES",
    "giám sát": "MANAGES",
    "theo dõi": "MANAGES",
    "monitor": "MANAGES",
    "quản lý và giám sát": "MANAGES",
    "điều phối": "MANAGES",

    # Integrate
    "tích hợp": "INTEGRATES",
    "kết nối": "INTEGRATES",
    "liên kết": "INTEGRATES",
    "đồng bộ": "INTEGRATES",
    "sync": "INTEGRATES",
    "nối": "INTEGRATES",
    "kết hợp": "INTEGRATES",
    "tích hợp với": "INTEGRATES",
    "api integration": "INTEGRATES",

    # Support / Assist
    "hỗ trợ": "SUPPORTS",
    "trợ giúp": "SUPPORTS",
    "giúp": "SUPPORTS",
    "hỗ trợ người dùng": "SUPPORTS",
    "hỗ trợ khách hàng": "SUPPORTS",
    "hỗ trợ vận hành": "SUPPORTS",

    # Process / Handle
    "xử lý": "PROCESSES",
    "xử lý dữ liệu": "PROCESSES",
    "xử lý thông tin": "PROCESSES",
    "xử lý yêu cầu": "PROCESSES",
    "xử lý đơn hàng": "PROCESSES",
    "xử lý quy trình": "PROCESSES",
    "thực hiện": "PROCESSES",
    "thực thi": "PROCESSES",
    "chạy": "PROCESSES",
    "vận hành": "PROCESSES",

    # Automate
    "tự động hóa": "AUTOMATES",
    "tự động": "AUTOMATES",
    "automation": "AUTOMATES",
    "tự động hóa quy trình": "AUTOMATES",
    "tự động hóa công việc": "AUTOMATES",

    # Analyze / Report
    "phân tích": "ANALYZES",
    "phân tích dữ liệu": "ANALYZES",
    "thống kê": "ANALYZES",
    "báo cáo": "REPORTS",
    "tạo báo cáo": "REPORTS",
    "xuất báo cáo": "REPORTS",
    "dashboard": "REPORTS",
    "theo dõi và báo cáo": "REPORTS",

    # Optimize / Improve
    "tối ưu": "OPTIMIZES",
    "tối ưu hóa": "OPTIMIZES",
    "cải thiện": "OPTIMIZES",
    "nâng cao": "OPTIMIZES",
    "cải tiến": "OPTIMIZES",
    "hiệu quả hơn": "OPTIMIZES",
    "giảm chi phí": "OPTIMIZES",
    "tăng hiệu suất": "OPTIMIZES",

    # Search / Query
    "tìm kiếm": "SEARCHES",
    "tra cứu": "SEARCHES",
    "tìm": "SEARCHES",
    "search": "SEARCHES",
    "query": "SEARCHES",
    "lọc": "FILTERS",
    "filter": "FILTERS",

    # Create / Add / Update / Delete (CRUD-ish)
    "thêm": "CREATES",
    "thêm mới": "CREATES",
    "tạo mới": "CREATES",
    "cập nhật": "UPDATES",
    "sửa": "UPDATES",
    "chỉnh sửa": "UPDATES",
    "thay đổi": "UPDATES",
    "xóa": "DELETES",
    "xóa bỏ": "DELETES",
    "loại bỏ": "DELETES",
    "hủy": "DELETES",

    # Approve / Workflow
    "phê duyệt": "APPROVES",
    "duyệt": "APPROVES",
    "xét duyệt": "APPROVES",
    "chấp thuận": "APPROVES",
    "từ chối": "REJECTS",
    "từ chối yêu cầu": "REJECTS",

    # Notify / Alert
    "thông báo": "NOTIFIES",
    "gửi thông báo": "NOTIFIES",
    "cảnh báo": "ALERTS",
    "alert": "ALERTS",
    "gửi email": "NOTIFIES",
    "gửi tin nhắn": "NOTIFIES",

    # Migrate / Convert
    "chuyển đổi": "MIGRATES",
    "migrate": "MIGRATES",
    "di chuyển": "MIGRATES",
    "chuyển dữ liệu": "MIGRATES",
    "chuyển hệ thống": "MIGRATES",
    "nâng cấp": "UPGRADES",
    "upgrade": "UPGRADES",

    # Secure / Protect
    "bảo mật": "SECURES",
    "bảo vệ": "SECURES",
    "mã hóa": "SECURES",
    "phân quyền": "SECURES",
    "kiểm soát truy cập": "SECURES",

    # Train / Learn
    "đào tạo": "TRAINS",
    "huấn luyện": "TRAINS",
    "học": "TRAINS",
    "training": "TRAINS",

    # Other common business verbs
    "tính toán": "CALCULATES",
    "tính": "CALCULATES",
    "đánh giá": "EVALUATES",
    "kiểm tra": "CHECKS",
    "kiểm toán": "AUDITS",
    "lưu trữ": "STORES",
    "lưu": "STORES",
    "backup": "BACKUPS",
    "sao lưu": "BACKUPS",
    "khôi phục": "RECOVERS",
    "restore": "RECOVERS",
}

RELATION_RULES = {
    # ORG → SYS
    ("ORG", "SYS"): {
        "default": "DEVELOPED_BY",
        "triggers": {
            "muốn": "WANTS_TO_DEVELOP",
            "cần": "WANTS_TO_DEVELOP",
            "xây dựng": "DEVELOP",
            "phát triển": "DEVELOP",
            "thiết kế": "DESIGN",
            "tạo": "CREATE",
            "triển khai": "DEPLOY",
            "cài đặt": "DEPLOY",
            "sử dụng": "USES",
            "vận hành": "OPERATES",
            "quản lý": "MANAGES",
            "quản trị": "ADMINISTERS",
            "tích hợp": "INTEGRATES_WITH",
            "kết nối": "CONNECTS_TO",
            "nâng cấp": "UPGRADES",
            "migrate": "MIGRATES_TO",
            "chuyển đổi": "MIGRATES_TO",
        }
    },

    # SYS → FEATURE
    ("SYS", "FEATURE"): {
        "default": "HAS_FEATURE",
        "triggers": {
            "quản lý": "MANAGES",
            "tích hợp": "INTEGRATES",
            "xử lý": "PROCESSES",
            "tự động hóa": "AUTOMATES",
            "hỗ trợ": "SUPPORTS",
            "cung cấp": "PROVIDES",
            "báo cáo": "REPORTS",
            "phân tích": "ANALYZES",
            "theo dõi": "MONITORS",
            "giám sát": "MONITORS",
            "tạo": "CREATES",
            "lưu trữ": "STORES",
            "tìm kiếm": "SEARCHES",
            "lọc": "FILTERS",
            "phê duyệt": "APPROVES",
            "thông báo": "NOTIFIES",
            "tính toán": "CALCULATES",
            "tối ưu": "OPTIMIZES",
            "xuất": "EXPORTS",
            "nhập": "IMPORTS",
        }
    },

    # ORG → FEATURE
    ("ORG", "FEATURE"): {
        "default": "USES_FEATURE",
        "triggers": {
            "muốn": "WANTS_FEATURE",
            "cần": "NEEDS_FEATURE",
            "quản lý": "MANAGES_FEATURE",
            "sử dụng": "USES_FEATURE",
            "theo dõi": "TRACKS_FEATURE",
            "báo cáo": "REPORTS_ON",
            "phân tích": "ANALYZES_FEATURE",
            "tối ưu": "OPTIMIZES_FEATURE",
            "cải thiện": "IMPROVES_FEATURE",
        }
    },

    # ORG → ORG
    ("ORG", "ORG"): {
        "default": "ASSOCIATED_WITH",
        "triggers": {
            "hỗ trợ": "SUPPORTS",
            "hợp tác": "COLLABORATES_WITH",
            "cung cấp": "SUPPLIES",
            "mua": "BUYS_FROM",
            "bán": "SELLS_TO",
            "phục vụ": "SERVES",
            "quản lý": "MANAGES",
            "báo cáo cho": "REPORTS_TO",
            "thuộc": "BELONGS_TO",
            "là đối tác của": "PARTNERS_WITH",
            "cạnh tranh với": "COMPETES_WITH",
        }
    },

    # SYS → SYS
    ("SYS", "SYS"): {
        "default": "INTEGRATES_WITH",
        "triggers": {
            "tích hợp": "INTEGRATES_WITH",
            "kết nối": "CONNECTS_TO",
            "đồng bộ": "SYNCS_WITH",
            "liên kết": "LINKS_TO",
            "gọi": "CALLS",
            "sử dụng": "USES",
            "phụ thuộc": "DEPENDS_ON",
            "thay thế": "REPLACES",
            "nâng cấp từ": "UPGRADES_FROM",
            "migrate từ": "MIGRATES_FROM",
        }
    },

    # FEATURE → FEATURE
    ("FEATURE", "FEATURE"): {
        "default": "RELATED_TO",
        "triggers": {
            "liên quan": "RELATED_TO",
            "dựa trên": "BASED_ON",
            "phụ thuộc": "DEPENDS_ON",
            "tạo ra": "GENERATES",
            "sử dụng": "USES",
            "kết hợp": "COMBINES_WITH",
            "tối ưu": "OPTIMIZES",
        }
    },

    # SYS → ORG
    ("SYS", "ORG"): {
        "default": "USED_BY",
        "triggers": {
            "phục vụ": "SERVES",
            "hỗ trợ": "SUPPORTS",
            "dành cho": "DESIGNED_FOR",
            "sử dụng bởi": "USED_BY",
            "quản lý bởi": "MANAGED_BY",
        }
    },

    # FEATURE → SYS
    ("FEATURE", "SYS"): {
        "default": "IMPLEMENTED_IN",
        "triggers": {
            "trong": "IMPLEMENTED_IN",
            "của": "PART_OF",
            "thuộc": "BELONGS_TO",
            "được hỗ trợ bởi": "SUPPORTED_BY",
        }
    },

    # FEATURE → ORG
    ("FEATURE", "ORG"): {
        "default": "USED_BY",
        "triggers": {
            "dành cho": "DESIGNED_FOR",
            "phục vụ": "SERVES",
            "sử dụng bởi": "USED_BY",
            "quản lý bởi": "MANAGED_BY",
        }
    },
}